# fly.toml app configuration file generated for htmx-axum-leptos on 2023-07-05T23:36:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "htmx-axum-leptos"
primary_region = "lax"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

[services.concurrency]
  hard_limit = 200
  soft_limit = 150
  type = "requests"

[[services.ports]]
  handlers = ["http"]
  port = "80"

[[services.ports]]
  handlers = ["tls", "http"]
  port = "443"

[[services.tcp_checks]]
  grace_period = "10s"
  interval = "15s"
  restart_limit = 6
  timeout = "2s"

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/healthcheck"
  protocol = "http"
  timeout = 2000
  tls_skip_verify = false
  [services.http_checks.headers]
